global:
  scrape_interval: 15s

scrape_configs:

  - job_name: "jenkins-node"
    static_configs:
      - targets: ["172.31.32.106:9100"]

  - job_name: "tomcat-node"
    static_configs:
      - targets: ["56.66.198.215:9100"]

  - job_name: "jenkins"
    metrics_path: /prometheus
    static_configs:
      - targets: ["172.31.32.106:8080"]
